openapi: 3.0.0
info:
  title: API de Métriques Kanban
  version: 1.0.0
paths:
  /:
    get:
      summary: Route de base
      responses:
        200:
          description: L'API fonctionne correctement
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /issues:
    get:
      summary: Récupérer les issues d'un dépôt GitHub
      responses:
        200:
          description: Réponse réussie avec la liste des issues
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 3442292533
                    number:
                      type: integer
                      example: 28
                    title:
                      type: string
                      example: "chore: Workflow Intégration Continue"
                    state:
                      type: string
                      enum: [open, closed]
                      example: "open"
                    body:
                      type: string
                      description: Description de l'issuen (texte en markdown)
                    user:
                      $ref: "#/components/schemas/User"
                    assignee:
                      $ref: "#/components/schemas/User"
                    assignees:
                      type: array
                      items:
                        $ref: "#/components/schemas/User"
                    labels:
                      type: array
                      items:
                        $ref: "#/components/schemas/Label"
                    milestone:
                      $ref: "#/components/schemas/Milestone"
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    closed_at:
                      type: string
                      format: date-time
                      nullable: true
                    html_url:
                      type: string
                      format: uri

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
        html_url:
          type: string
          format: uri
        avatar_url:
          type: string
          format: uri
        type:
          type: string
          example: "User"

    Label:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        description:
          type: string

    Milestone:
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        due_on:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
