openapi: 3.0.0
info:
  title: Kanban Metrics API
  version: 1.0.0
paths:
  /:
    get:
      summary: Home route
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /issues:
    get:
      summary: Get all issues
      responses:
        '200':
          description: List of issues
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    url:
                      type: string