name: Add issue to user project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read

    steps:
      - name: Add issue to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            // 1. Get the project ID
            const queryProject = `
              query($login: String!, $number: Int!) {
                user(login: $login) {
                  projectV2(number: $number) {
                    id
                  }
                }
              }
            `;
            const variablesProject = {
              login: context.repo.owner,
              number: 2 // change to your project number
            };
            const project = await github.graphql(queryProject, variablesProject);
            const projectId = project.user.projectV2.id;

            // 2. Add the issue to the project
            const mutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;
            const variables = {
              projectId: projectId,
              contentId: context.payload.issue.node_id
            };
            await github.graphql(mutation, variables);
            console.log("✅ Issue added to project");
