name: Add new issues to GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Replace with your project number and org/user
            const projectNumber = 2; // your project number
            const owner = context.repo.owner;

            // Get the project ID
            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const project = projects.find(p => p.number === projectNumber);
            if (!project) {
              throw new Error(`Project #${projectNumber} not found`);
            }

            // Add the issue as a card in the project
            await github.rest.projects.createCard({
              column_id: project.columns_url.split('/').pop(),
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
