name: Add issue to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read
    steps:
      - name: Add issue to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            // Get the project ID for the user project #2
            const projectQuery = `
              query($login: String!, $number: Int!) {
                user(login: $login) {
                  projectV2(number: $number) { id }
                }
              }
            `;
            const projectVars = { login: context.repo.owner, number: 2 };
            const project = await github.graphql(projectQuery, projectVars);
            const projectId = project.user.projectV2.id;

            // Add the issue to the project
            const addMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item { id }
                }
              }
            `;
            await github.graphql(addMutation, {
              projectId,
              contentId: context.payload.issue.node_id
            });
            console.log("Issue added to project");
